### PR TITLE
Load Builds from URL hash

### PR DESCRIPTION
**Pull request by theastrogoth**
Related #27

### CODE REVIEW

**Comment by theastrogoth** [comment]
@Ericzklm The ability to load builds from the URL hash is now currently deployed (from this PR's branch). Does [this link](https://theastrogoth.github.io/tera-raid-builder/#H4sIAAAAAAAAA91YbW/bNhD+KwY/rRhd6MXyS78lcbNkaJosDlBghj/QEm1zlkSXlOIYRf5770i9pk7sdVkwDEmkE+94PD58eDzmG1mQDyT8S8uUUJKRD9OpQ4lDZhTfS54WUsoSXogbueaJNc9VqovWXHN1OcZGppY8A9G264xl0BquWLosPYgIWhJ5zy/ThQRxLrW+Kj+tSagEdtM8lGnE1O7jYsHDTEOTknGMRgElcpMJmerC2ZhlrFBUn7WNdbsWKY5tAjBTgnh3G44u5kzzCQSL8paL5SpbL4teqw20sWwNz4gvMKwNM8/IPMtppXmCdnMRi0wYnyLjSRmetrah1ZSjpgxA5CY81212LhpMVFWvltoHlFjGl1LtKtgLzwRXacsVdgnDXLEQTTZKSIAVxUgxgSu44iwW6dIgHS/GLGFL7MxEnPDULAAgcmbWDsdfgHG4wu+QN5Rho0/1nYj0Qhg0E/ZgJIjZq2D/EYoKdEpifs/jkhh5nIlNLMxsgJCRnZZBYldL1zgdocc78M8eOK5MZOVPhTOhJyzOzgBu7BWDR30OKGTGdi6lBmli2YrrhpFxxe4snEL/cVMtF37fY8jcPE1fQ022LRmkizcAvhQpi2HYi5uiPTezlg8iPJM5jK8aDDHMBIrjGPwhU+yqVOiPaWTHjpnOsLkQ7+zKz2aU3JMP3wjs4R6dmrc7oPbt05GVPDqaPf59cfYIErkVccxgtoCNddujpCanqrVNyyn5TTGNq2/7eNR1HOp6AR05tO/QgUOHAXiHL2tAyfU9V0slt8QMWzsAE+zrB/AgVzCMUew6k1whbRcs1rx4pnkcN8X6QT5LlTAgRPHFcmDdjlTR+e6T3xID0Dn1z8FW1x35AXTvUc/tUzfAvyH1nP6RNlZHCLidkju25p2x3CLJv0gZdS5YkhjinIRKzlkmQlyCscqTzimHzxRzF6B0y0TUOYVtBAsxewpIFcnr0uSO5Urq7g2LI866J19z1j1VHLeZHSVosiYzxhtjy8B0bi1fcDIl55gobNr6wnD/1NwaBAAc0gRgNdwCwkBMw+H7XumTVDy7TDORiAhclEzb49l0NZQtWXcC2VB1bqTADHmQdOSTWPDOtZqTZuPvcIodTTovKEkG0kHieSN0MKJer0+HwKhBn/re8BgDVBSEq5LNLWRPpRkeuaA8heDfkElXXG51yBSL2N6UkzT1besya8CmYGrdZEjfMATTjmsI4vkwlO++9w7kn8qTsfX7NSF++Sw7J/YYencMI85lmOvOhOlVixMTDgd0rv+NVOTSUUD7fTro4dN1ege12Fpw4TzGWqJzp0SI0/cs0m9IgzOp7sU6xb25lwZhU9+2xuh3dkNPMs7jBhFGQzocmEwR+HAE0f4AxoL8UbLgBuoyjZugzA1PHWGuaeaFqsMRFPgTzsbOJ47Fa6P1MtkIJMUxBLBJoUoNB0nQgzA9IL7vj4DzAzxlYOsfZ4GaggyTELJwuMJtYKF+Qx5cQvHH4bd7vvcoEYUaK/Sm6ZTc6F24EiGpDv9GOnBoAGsf4BZALphaxBs2PFzVB8b1Nu3c8WQjS07scQx926ywJkcXKc9lh1MZR6+fGjxIgi44cIcge31zJrRrlOctUFOw4oLHG9gcUJbA/WpGYXeOOd/PjFlRmw5oUfDBQQRHixGHLXjwCkGqSPq0nYigvi+vK3B3gcshj7r11XRpU/bAKflDa+mV3oYCxQycegaZyusJsIfWBFrF2kvhL4pcE9gUY3+ei2evthnfoIwOK6PSFOOpTvk8FV9zI2hTVaZFjfx0qN7PBPLC2lbgODWEGFirkC2h+jUu7rTPr/fQeQEvy7u+vbLTrotcLO0PBG0WtVjOJq5eFb7fxLVMkgAkz7pLKNi75YVwT+xPwYaz6MAEzH8hup6dwGth3r5XHLG5XK9Er+v7P0+LHzdME2G/CrbXDLaVcBr8Zaasfpa/wRvx97+JZe9/xNY3TaXHwRtUkbaSbHWDOhBndfUsh//H4R4Jp29vMPgvpXfkud7VbGezx8fvo2IPfjYWAAA=) work for you? It should pull up a strat with Psychic Surge Indeedee.

The links end up being a bit cumbersome in length, so your suggestion to have some official builds with a short hash is a good idea for easier sharing.

**Comment by Ericzklm** [comment]
Yep I see the Indeedee! I've tried changing every field and exporting the result and it seems that everything but the additional move section is being properly filled. The URL is quite long though but theres probably no way around this without a database.

http://localhost:3000/tera-raid-builder#H4sIAAAAAAAAA+1Y23LbNhD9FQ6e2inUES+65S2S4sRtHLuRM3nQ6AEiQQkVRagEaVvJ+N+7C4AUdbHCup6mDxnLJIjr2bOHiwW/kpi8IuGfSqaEkpy8mk7blLTJjOJ9wVNbStma2+JGrvjadC+yVNnaQvHscoyVLFvwHIqmXuUsh9pwydJFOYOIoGYt7/hlGksozqVSV+Wj6RJmAocpHso0Ytn2TRzzMFdQlckkwU4dSuQmFzJVdrIxy5ltqB53fcy0K5Hi2hqANgnwbjccp5gzxScAFsv3XCyW+WphRy03UMfyFVwjHiOsDdPXSF9Ls9Jijf3mIhG50HOKnK9LeMr0DU1LuWrKgESu4blufbCtkPmSZxcyW+vee80+sMRyvpDZtqLdzkzQS/c8wyFhWGQsxC6bTEigFYtRxgR6cMlZItKFZjqJx2zNFjiYiWTNU+0AYGSkfYfrx9A5XOJzyGuNYW1M9bwW6Tuh2VyzB10CzF5F+zEVFemUJPyOJ6UwiiQXm0Roa0CQkTFLM7Hdla7RHKHGW5ifPXD0TGTK7+1kQk1Yko+AbhyVwIzqAljIdd+5lApKE6NW9Bsi4xm7NXQK9cdN5S58vkPIXF/1WC1Ndl8qSNk7EL4QKUtg2Xc3tr7QVssHEY5kAetnNYVoZYLEcQ3+kGfsqmxQb9LIrJ0wlWO1Ld4az89mlNyRV18JvMMBneq726Pm7tOBKXl0MHv858XZI5TIOGMLtgF/EDttQMmk8mO0a633nOoHHS/eLoEokIEZ7NF+n7pem/Y61G2bW+DBOp227UHJKOEsc4Yy2hIN4cRk0Bt+XgdmIFdQD0wrHpkxNGaJ4vaaFklSL+oLGS2lCLmDZqARl6hd03IlI64qUz3qDQ5+JTnQ1qVtiiA8c621tHd/tdqgjdZ6HToIqNvt6tvAb9JBNxAC803JZMkiee8MQcyWc5k6NwVYCI+fWrcQnqFwkcAbly8zHRBmMJB8WiRbsBhiAXfesTsU4JS8x7fPmYQZ5zjqI48TiLhQmhRZrG9zlYu8yDHcHdBYAX9ZvV2JtVhti9IFnbra1mXbrtfUagJMZgKC4k5oHeCxTftaKW4bHrowffvXHgyxo1vDAt//agzQKdSiEEClFd7h3DgcZeuWwqsGNFDdexFz5zqbVzq29a8jiFhpXXR96oOkuuB9oNTr1iTiBrB4D1uCI32dVp3X9+E/oJ4/oC7sLp4HZc9v1ANbrOxeq1ymQi0B/JDNt84YdmTnzVa7ZVgkK+cT7pewEWRr4AmofHv9+tZxwUE/hGOFMxg8TzefOVulXCnnRiZCb+pmVtv8G3hiuxMPKmeAEvJ6KCGvU1cPBBXfCMUdeBiHG8gHZgIdugMXxAFT9mHOnt+oB7ZY+YxkGkO26HxkiH8kN9tQb7o6cCMfLFvZKDajnlWP90M9NfX0n6ee6zBkzpBnOmGc5BzTIrsLsozHRbInnf1fzcs+bk9m54bo0wULv73heR0ILDAC/12/AxOCMgKvUQ9ssdoZsy9fMGF13kJigCnaGLZokW5hu9eJ/VgW84Q7t7YRs1yQEuSswJxvpeT/kFJNSr3nScmmTUOmaf/MdBZrmi7XG705nBdEm3Z3+VKTvQs84oL9XgCegY2pq6NMkw7YUMoHBYHy+V0odEGVUl+wkEW6oI9DMxpYsQSnxTKzCXaP2lwVFoNYpYt9mmdFyR4eg0iFskvrm2dUHrfg7AWpFo9au6P1wvjKN/mF+bO6Orr7J5u10y02mKXEZmBphHgw28O2n08aeL8k9iD5NMj+OZCGp649Lbdc5A6c9ATg8qlXAnahb9kVIe62iyIVfxXIHn55wKMZHJJZGcFqAM5z9wR1J9nSnqz4au9YRWAH2fc530b2CNPvNHDuNwDuSU27s06iV2H1QdE7rIdRtEILnm/JzUamcJLXB36TXZz18HOQnqWyOrmcI3FeLAjtvTSuIwb9CmJQh3hhv5qcdTPkMTs5/muczaW4d+Cr3uPaN51jrLHAMDg4RScwjc6oo3SbwjyiM6gQu+USEJx/+iAd/KDxMzlwSxNrD86tseBJ1OL6c6ENDqqlK/ELmNqGSxG+cJCoQz2yuHMcx56wuL7pfsPm3eH8O5i7j/PI4G4t5ryYwfYbxH6cwk+jNQ3fmyTkpIhf1sReBTJ4SROr7yv/6eb2pJX9xu9qQysbjT6CMfh/wChj3nfH4X5fHLPZ4+Pf26Fx5TUaAAA=

**Comment by Ericzklm** [comment]
How forwards-compatible are the URL hashes? If you were to add a new feature like move grouping which changes the data objects, would a hash from an older version no longer work?

**Comment by theastrogoth** [comment]
> How forwards-compatible are the URL hashes?

As long as new features don't require changing the way things are already structured, adding additional data to the URL should be fine while maintaining compatibility with links from older versions.


> Yep I see the Indeedee! I've tried changing every field and exporting the result and it seems that everything but the additional move section is being properly filled. The URL is quite long though but theres probably no way around this without a database.

I think I've fixed the Extra Moves bug, and I've managed to shrink the URL hash length by roughly half by getting rid of 1) a bunch of extra info that the smogon calcs make use of (e.g. Pokemon weight in kg) that wasn't needed and 2) information about a used move other than its name. 

http://localhost:3000/tera-raid-builder#H4sIAAAAAAAAA7VU30/bMBD+VyzvZZM8iTbtkHhbYQykgVDLNGlVH67JlXh14sh2Ch3if+fO+dHCHsbEUCPXvvPd9313l9zLlTyS6S9vS6lkkEfz+YGSOpMLxZvKrrFoXLUrPVsHShZ2g+flypJ5ab2/6I5NTOp0II/H1JYZuO2X1QrT4MnkrDHtpRIKJEvt0Z2fcHpwNxji1lZB2waLLuYVmSCsac1wxXkriGsWV2wpUWrO16aFpTY6bGmnAxbRTvzZgxsmouNqcIOGsdHB9bZiNytjF94FBxfxsFgouZFH95JqM1Tz+H+oiNkUdCYmpJ/uT7UxsLSWsb468H4rZjUpkqqsjVHyEuqbnAnF8E8U3v8WD50xGTx7yDU4IKRL6wogpnN5DWsUJ/aWO/LD2kycQVGgo9Pn1NklBJ0ynRNXF2KCdCxvuECUYWlQTC3w1WuoS+7QhPgua+cDaWxJHKpBIwydeDegOxeY6TQH1nVFFRRX9jbCndq09mIGPmfsDArglL264XjY6qPd3xXGIs3lld+mufjOHZ9Sb5yHOC577IY7dkMG/l0X4Kj2tJ9BJWa6qpheU/TzotLMrwVvOPXMXsxqgsZsBZf0GZlkRyYhAsfWbfS61NRorpZD75uZ+0l1Ft+w5M78J06z1CGm+TNCox2hEWOVGSI9H0+ZD9dWp91YPm3gxJrs1ZzO0FQ0bzSSZdYSW7TvS0JjFTdjtV9OxRDRPlIrMB7bVRa6lBT90AftT/dBl2ykgqt3MXAXY7qopMs9VnuDNSDM1yA+DfoDctjHdx1SyUs1PnmfXywy2TEOAdK1OM6RE4zeFnb8CqHvL63gb+uHf6nsqA/vPw0U+xaINLcPj0OeMTwXBwAA

The links are still quite long, but at least now they're under the ~2000 character limit that is common for URLs.

**Pull request merged**
