### PR TITLE
Fixes relevant to Iron Bundle event (and others)

### LINKED ISSUE #172: Dragon Cheer
Dragon Cheer boosts ally critical hit ratio but not the user
+1 if the ally is not Dragon type, +2 if they are
I think the +1 and +2 are both considered the "pumped" status and will fail if the ally is already "pumped"
More testing may be needed

### PR DESCRIPTION
**Pull request by theastrogoth**
Changes:
- Required Snow for Aurora Veil to have any effect
- Implemented Court Change
- Implemented freezing and thawing
- Changed paradox abilities to no longer be unsuppressable or unreplaceable 
- Added screen-breaking effects to Brick Break, Raging Bull, and Psychic Fangs
- Fixed strat loading from json files
- Prevent Competitive/Defiant activation by allies
- Added Water Bubble
- Added check for unsketchable moves
- Added Palkia/Dialga strats
- Added Iron Bundle strats
- Fixed Dragon Cheer (closes #172)

### CODE REVIEW

**Comment by Ericzklm** [comment]
Something weird is happening when loading strats

Also the Steely Spirit Gholdengo and Metagross strats fail in the test suite

**Comment by theastrogoth** [comment]
> Something weird is happening when loading strats

I'm noticing this, too. It might be due to some of the changes from trying to get Transform/Mimic to work. I'm taking a look now.

Regarding #171, YETI's strat as currently saved in the builder seems to work if Ston gets Power Spot. I've logged each move, and it seems like stat changes are being properly applied after each hit.

**Comment by Ericzklm** [comment]
> Regarding #171, YETI's strat as currently saved in the builder seems to work if Ston gets Power Spot. I've logged each move, and it seems like stat changes are being properly applied after each hit.

Whoops I somehow have it in the link in the issues but not in the version in TRB. I can fix that in the next commit since there's a couple more strategies to be added anyways.

**Comment by theastrogoth** [comment]
Screens were the culprit for the failing tests. Their damage modifier is controlled by the `gameType` parameter of `Field`, which doesn't affect anything else as far as I can tell.

**Review by Ericzklm — APPROVED** [review]

**Pull request merged**
