### PR TITLE
Graphic Header Tweaks

### PR DESCRIPTION
**Pull request by theastrogoth**
Allow long titles to overflow to the next line.

Add boss tera icon partially overlapped by boss art

### CODE REVIEW

**Comment by Ericzklm** [comment]
For the boss' tera type I was thinking of having the banners:
image
The issue is I cant find a high quality version of them readily available

**Comment by theastrogoth** [comment]
I tried tracing the shape of the banner at a higher resolution, using the Normal colors. We could recolor it and put the type symbols and text on top if we want to make them ourselves. 

I'll add them to the assets once I've finished putting them together

raid_banner

normal_banner

steel_banner

**Comment by theastrogoth** [comment]
Example of a new graphic header with a tera banner sticker:

header_draft

**Comment by Ericzklm** [comment]
Slightly increased the borders on the banners

**Pull request merged**
