### PR TITLE
Add Link to r/PokePortal

### PR DESCRIPTION
**Pull request by theastrogoth**
Peppers reached out to ask for some additional advertisement for the subreddit. I added a link image in some of the blank space near the top of the page: 

rpp_link_image

Alternatively, this could be at the bottom of the page above the acknowledgements.

### CODE REVIEW

**Comment by Ericzklm** [comment]
I think it would make sense to keep it at the top. How does it look integrated into toolbar?

**Comment by Ericzklm** [comment]
I noticed the link takes you to the front page of the sub, should it link to the raid post or directly to the chat? A few issues with doing that though would be that you might need to already have an account logged in to directly access that chat and linking the raid post would require constant updates.

**Comment by theastrogoth** [comment]
I've changed the link to take you to the directory instead of the front page. That should hopefully be direct enough without needing frequent updates or a logged-in account.

Here's how it looks in the toolbar. If the page is too narrow to fit everything, the other toolbar buttons get moved to a dropdown menu:

Screenshot 2024-03-14 182151

There's also a link underneath the create link / graphic buttons with a short blurb that gives some context.

**Comment by theastrogoth** [comment]
On second thought, I don't like this very much. Hiding the pretty/edit mode button on mobile seems like a bad idea

**Pull request merged**
