### PR TITLE
Symbiosis fix

### LINKED ISSUE #88: Symbioshrimp Test Case
http://localhost:3000/tera-raid-builder/#H4sIAAAAAAAAA71VS2/bMAz+K4ZOGyBgzastemvabU3XdluzYYcgB9mmEy2yZOiRNCv630cqduMMPaRAM8RRKIrk95EinUdWsDOW/XZGM848O5tMjjjTogQ25STKvBYyKz2aOMiMzoVdfywKyLxDlTVKkVGHs+DAji4pkrAz8FE0lZdGO7LocjazJlSoLc0SRrowKKbGudtmu4mjjQcKnVnIZQSpzALKDclgNWliJFezm1NM4Re45lAQz0rENY8r1OhIFVidH9qnUkm/Rkl6KKMeg9MJLAlBxlXBEhThghU/1hXU5F3DPCgvKyXBkt+Dt+I2nk6nnC3Z2SPDmh5zNp5bWVbSOEmO+IQPF6hy9xDz4QntHjxFmUSfU45p3QuZJ0NEQYd7qZRIjSGin61wbp2MA1aZcR2U4uwarwFzic4n6Pz8mT41yl7nnwePOkeIc2dsKTDJCbu0oUyGILzUMwQ6z6xJcZMRg6HJEVMJYnBjVskXmS2wsL0BhpggJ7Py82hmyjRYR+0yDGqR/KywGjWJU47Xex3K1CSbkqDRhRIr6f/ECt7CTCQ3IuhsvtlLa41NrsCmtDM5UNxWkt1BN373SjRWasLOgxXJuEIEagw6mLQIYp98X0lVSEfZtMSR9rKUufDUA+/uTDLCtnkfM1b5M6kNmZrSa0hleNfjyor1C5x6nH1SBm+b7mErjddl2vTULxALDc4l34yS2fqtaF2BqrAXkiuh8xeI9Tn7aoWeBRvYjtimdjE3MgNMDuo+egNeI+28DZlvcZrWozPgtVXc9Td3RVOJd9XBs6ju8UIoB/XKSqkZRnh69mna+QhdagfEg83CSvEQzRuHAVrtQF5CAdoBjjVQH/f3hd2dv33Bu014jHDuvcgWDXDvsMC9NvC2gbeEDgPbb+z6fNsIqO0eEnTQAt2ZCqxC55DAxy3g/1jkk92Obr809x+j10HjBOPfdA9/KOv+FIf66S91NwKqowgAAA==

I figured this would be a particularly gnarly test case. Symbiosis not working

### PR DESCRIPTION
**Pull request by Ericzklm**
Added symbiosis check between moves

Resolves #88

### CODE REVIEW

**Comment by Ericzklm** [comment]
I've added an additional check for symbiosis between moves.

Modifications made to symbiosis: ignore lost item if the lost it the Pokemon that lost the item has symbiosis, do not assign a symbiosisID if the symbiosis Pokemon does not have an item.

Are the raiders supposed to be sorted by speed? The algorithm just seems to iterate through indexes 1-4 and favor the latter slots regardless of speed.

**Comment by theastrogoth** [comment]
Wait, shouldn't Symbiosis trigger at the end of Rillaboom's move? I'm not sure why we'd need to have an extra check between turns. 

Maybe having a loseItem(id) method that removes a held item and checks for relevant abilities is a cleaner solution. 

I'm also wondering if moving a lot of these methods to the RaidState class would give us more flexibility in applying things at different times in a move/turn/battle without having to write more code. I might open a PR for this when I get the chance.

The intention was to respect speed order, yeah. id number should only be used as a tie-breaker

**Comment by theastrogoth** [comment]
It looks like there might also be an issue with Mirror Herb activation.

This has to do with loading from the URL hash. Sometimes, the MoveData isn't fetched before the calc is run, so all of the stat changes for moves (like growth) aren't there. Another separate PR

**Comment by theastrogoth** [comment]
> Are the raiders supposed to be sorted by speed? The algorithm just seems to iterate through indexes 1-4 and favor the latter slots regardless of speed.

I'm not able to replicate this. I swapped Oranguru and Florges in slots 3 & 4, and the results end up the same, so the Weakness Policy is passed first in both cases.

**Comment by Ericzklm** [comment]
I did notice that issue with the URL hash, if you go into edit mode, everything gets recalculated and it should work again.

Now that I think about it, the item loss check happens before and after a move so there shouldn't need to be a mid turn check. I'm guessing the choice specs isn't passed because there's not a check in place if the symbiosis Pokemon doesn't have an item. It worked in the mid-turn symbiosis proc because there's an extra check added that doesn't add the symbiosisID if the symbiosis Pokemon's item is undefined.

**Comment by Ericzklm** [comment]
Seems to work after adding the item undefined check and removing the mid turn stuff.

For the speed order I was thinking about who the item gets transferred onto but that actually shouldn't be a concern since everything is asynchronous. Oops.

**Comment by Ericzklm** [comment]
I think we need to follow up on the RaidState restructure and the MoveData loading but everything this PR was focused on should be fixed

**Pull request merged**
