### PR TITLE
Move UI sprites

### PR DESCRIPTION
**Pull request by theastrogoth**
Add box sprites to the pretty-mode display of raid moves:

move-ui-sprites

### CODE REVIEW

**Comment by theastrogoth** [comment]
I've moved things around a bit so that box sprites will also fit in Edit-Mode:

move-ui-sprites_3

Fonts are a little smaller to make room, but I think that the readability is improved overall by having the sprites there.

**Comment by Ericzklm** [comment]
image

Does this spacing look better? Increased the space between each item and the spacing between the sprite and the name.

**Comment by Ericzklm** [comment]
You can still barely overflow the box (Ignore the really wide unicode character). Pretty mode is still fine with the current spacing. I dont think anyone will name their Pokemon "MMMMMMMMMMMM" so this is probably just nitpicking.
image
image

What are your thoughts about moving the crit, effect, and roll into an expandable menu and defaulting to non-crit min-roll or crit max-roll? Could make the UI more compact since most times I dont change it to anything but the aforementioned defaults.

**Comment by theastrogoth** [comment]
> Does this spacing look better? Increased the space between each item and the spacing between the sprite and the name.

It looks better, but your image might have just a touch too much extra space. Perhaps slightly larger font for the bolded words would look good as well?

> You can still barely overflow the box (Ignore the really wide unicode character). Pretty mode is still fine with the current spacing.

I agree that it's not a huge concern, but I wonder if we could get ellipses to kick in so that the sprite stays visible. I guess it won't be necessary to worry about that if we come up with some more room. 

> I dont think anyone will name their Pokemon "MMMMMMMMMMMM" so this is probably just nitpicking.

There are a lot of food-based Pokemon, so you never know

> What are your thoughts about moving the crit, effect, and roll into an expandable menu and defaulting to non-crit min-roll or crit max-roll? Could make the UI more compact since most times I dont change it to anything but the aforementioned defaults.

I enable crits much of the time but mostly leave the other two options alone (unless I'm working on something wonky). If the boss was changed to crit + effect + max by default, I would almost never touch the options, so changing the defaults and moving them to an expandable menu is a good idea.

**Comment by Ericzklm** [comment]
I'm not able to change natures in this branch

**Comment by Ericzklm** [comment]
> It looks better, but your image might have just a touch too much extra space

image

What about something like this? (rough draft). Keeps the original spacing while differentiating each piece. I think the spacing between the sprite and the name would still be good to have though. 

> I agree that it's not a huge concern, but I wonder if we could get ellipses to kick in so that the sprite stays visible

Thats a good solution!

**Comment by theastrogoth** [comment]
I've played with the layout a bit after adding the move options to a separate menu, which opened up some space to spread things out a little. Things might still look a bit funny if you name something "WWWWWWWWWWWW", but even then everything should still be visible.

**Pull request merged**
