### PR TITLE
Add type interactions and failure conditions, other mechanics

### LINKED ISSUE #68: Type-based interactions
Implement special type interactions:
    - Prankster targeted on dark types
    - Powder moves on grass types
    - Paralysis effects on electric types
    - Burn effects on fire types
    - Trapping effects on ghost types (probably not relevant)
    - Thunder Wave on ground types
    - Ground immunity to sandstorm
    - Freeze effects on ice types (sheer cold not relevant)
    - Poison / toxic affects on poison types and steel types (except with corrosion)
    - Poison types remove toxic spikes on switch-in (not too relevant)
    - Rock immunity to sandstorm
    - Steel immunity to sandstorm
    - Flying / Levitate / etc interactions

### PR DESCRIPTION
**Pull request by theastrogoth**
Implemented so far:
- Type Chart immunities for damaging moves
- Immunities/boosts based on abilities (Flash Fire, Sap Sipper, etc)
- Immunities to non-volatile statuses based on type and ability
- Dark immunity to Prankster moves
- Ground immunity to Thunder Wave
- Powder Move immunity for Grass types
- Priority failure on Psychic Terrain
- Electric Terrain blocks sleep (?)
- Misty Terrain blocks non-volatile statuses  
- Safeguard blocks non-volatile statuses and confusion
- Mist blocks stat drops
- Bulletproof
- Flinches
- Grounded / Flying effects (move immunity negation and effects of terrain)
- Unswappable Abilities
- Protect, Detect, etc

To-dos:
- most volatile statuses (Drowsy, Taunt, Disable, Encore)
- Choice Locked

Other To-dos (lower priority?):
- Charge/Recharge moves (Solar Beam, Hyper Beam, etc)
- Rest checks
- Damp vs Self-Destruct, Explosion
- ensuring correct order for all checks

closes #68, #69

### CODE REVIEW

**Comment by theastrogoth** [comment]
Test case for immunity-granting abilities:

http://localhost:3000/tera-raid-builder#H4sIAAAAAAAAA7WUUW/TMBDHv0pkXkDyQ9N0MPVtaB1MooDo3qI8eMmlNXPs6Oy0K1O/O2c7WSmoUGlUjU722Xe//10veWI1m7LyuzWacebYNM9HnGnRACu4X8qqX5QoHV2xUBpdCdzO6hpKZ8mFRil/KeWss4C31z6TwCW4sDStk0Zbf2PM2RJN15K3MWu41bWh5b2xdj5sYx5tHPjUJUIlA6Q1D9BEkR1q7wmZbK9u5XMK90C2gtrrbEWwVbDQ00kqsL4+un8vlXRbWkkHTfBTcn8Ca0+QwSpYg/JcQHG3baEXbwflnXKyVRLQxz06FPNwWhScrdn0iVFP33LG+icPjktOmr8JWSXvKQUdzGFD9vVnk1xFUW8Y151SnH0UWJHEEPaOwp5/xW5wZulvDx2lo1FMkLOZQLdKvppNkHijqHi3wn676NC3ay6WshQq+QSipl756LwYCJc8jWoBk1cp3b760TUCpfJtWYg2Wci29dn+k+I/+eM9f0zML1TQxqD/y2JxM+HOys/2/MzXj6XQUkNsp10lN9KPzdnwkz1+QswPwjo0VXgbFo76kFyjkPoMAop+Xi94fxZ2kzipfs5pTFM6C+6M10JZ6C1rSBFl2D3HHMwYBaVDmMMOomGNeAxBQ9gF1X4MPD4VfDjyv4BjwDFy+nLywat3asXjo9zsxRX/FZwdBU9OBcfPyb+ARRiu3U9yawz8fQYAAA==

Test case for some type-based immunities:

http://localhost:3000/tera-raid-builder#H4sIAAAAAAAAA71T32vbMBD+V8ztZQMVYjvdSt46WljHspVSyIPxg2KfE7WyZCTZbSj533eS7abtCPNLi81xuh/f9511foIKFlDcWa2AgYNFls0YKF4j5My7ohycwghHJRYLrUpudpdVhYWzFDJaSl8UM2gtmqsLj8TNBl1wdeOEVtZXJAw2RrcNRWvd4ZWqNLlrbe1yPPY4Sjv00IXBUgSSRt9j3YtsjfKRgGQHdVuPyd092RIrr7PhwZbB4sBOUhGG+ah+LaRwO/KEwzrECdxnsPMMIliJHUrPi4bf7hocxNtReSudaKRA4/seneHLkM1zBh0snoC+6VcGMLxZCJwx0nzDRRl9JwhKLPGB7OffOjrvRX0BplopGfzgpiSJoe0btT0/+X4MpvGbl1LxbNYDZLASUp78OVkJ6z/S7bZVJZpoxTs/yrUWdPfRT76mwyU3bhtd6wcaJg8QWT7SnLG4l0y9n2IqPjc1pyvY4HsJ/1dBclCQeO1brprdx9GnB/qUWG+w453Ruv44BfODgjl4hla5sHi/sBOOO3wH7nzY2VM25MJp3s/sd50GjikXwimruLQ4WKiFAkLYP/e82sUZ9Q1dzrTYG6j5Y+gZu06p6hhvMpX39dZPJU6OEqdTiV/+X1Np06O086m0L//k//Lm4Z73fwEtdRw1DAYAAA==

**Comment by theastrogoth** [comment]
Test case for flinches:

http://localhost:3000/tera-raid-builder#H4sIAAAAAAAAA7WT204bMRCGX2Xl3hTJSMkuaRF3BEqJVNKIIvUiysVkPUnceO3Ih5QI8e6MvQ4hHCTUCu3KO2vPzP+NPb5jM3bC6j/OaMaZZyfjcYczDQ2yCY+mFNmorfTk4rA2WoDdfJvNsPaOpqxRKjp1OQsO7eA8ZgI7R59Ms/LSaBc9Ss7m1oQVzTZmjQM9M2ROjXNX2982jzYeY+raopBJZGWW2LSQweo4kzK5TLeIOcEvaRQ4i5wrSKNII2Z1QkWW6yP/qVTSb8iSHps0T8njCq6jgkyjwjWqqIsWbjYrzPBuSx6Ulysl0ca4W2/hKq1OJpyt2ckdoz39whnL7zhNHHNivgYpij6loIVrqRRMjYkU3y04tyl+BdpCxnVQirMhhPkioqbwrxT++Ezut5NV99lLS90OKQ2NbYBqGLMbWGJxbv7GjfxtjCguoWkS+mltzRS8rCPOuQ1N0Uf61XPauqpHWcbsIgb/DLENbiDo+O0T8jRY19qCqBU0VHtmOubdtk60xacu+YzkEupFIOvz0BSn7QEcbKu8BCv+scaUgOpbBB3FRkHXCyKPS+MnOOUOp2zLsMYdjkAJhMMzqgX8Yd8iig8jvEQQ0+D9K3DVDq4i/R+hBivjDRloTZMXpg4ucw2oYQmKXRmBcfOzdtkrE07+vhtqCM5vipEyPuePPXzwCuLRDvEoHrlF1Tbt/maxM4q3vjhTBuKd/JBtm+TL1OPZK/0R4X4TUAt22qWKz0A5zCNrpGaU5f4xbtffHQrKId6GXQTcpohtTI/c9pQfKXn5XDTlean59No9V80hL0TLfdGnh1f9f61vqVZvlXr0zlLfLzlJ53v/ALCiYR2dBgAA

Note: We currently don't have any check for moves that only can be used immediately on switch in (Fake Out, First Impression)

**Comment by Ericzklm** [comment]
You can flinch the raid boss; is this possible? I've always just assumed it would fail.

**Comment by theastrogoth** [comment]
> You can flinch the raid boss; is this possible? I've always just assumed it would fail.

No idea! You're probably right. I'll try a quick test.

Results: Fake out doesn't fail (the move hits as normal) but the boss doesn't flinch.

**Comment by theastrogoth** [comment]
Protection testing: 

http://localhost:3000/tera-raid-builder#H4sIAAAAAAAAA8WU32/aMBDH/5Xo9rJKfiAB2oo3qnZbpVGxtVIfUB7c5AIujp3ZDiqq+N93dsKv0kloKpuIzOV8d9+P7XNeoYABZM9WK2DgYDCZdBgoXiKkzJsib43MCEchFjOtcm6WN0WBmbPkMlpKHxQzqC2a22tfiZspumDqygmtrI9IGEyNrivylnqBt6rQZD5pa0fr16aO0g596cxgLoJIpedYNpC1Ud4TKtmWbuZrcjenMcfCc1Y8jHkYsVUnVIR2fRT/JKRwS7KEwzL4qbifwYVXEGGUuEDpddHwh2WFLbxdk9fSiUoKND7vxRk+CrNpymABg1egPT1nAO0zCY5LRsw/ucijKypBE9eGT7UiDLI/3+lo2KCdAVO1lAy+cZMTaEi+oOTNL12tnd34zUNTcafTFJjAEI3gMhpmXuKGGzf7VfN5eCFoLDG6rxD9afukSboufMniBhVN9Cmm8O91xo3QB6DwiHyu0NporKXI/LaOdI7WbbCTfhKg2/+j0e+4dctoLLVvwC86q210JbkvDGNDnZK5d6iTLXVCgfdOq2dNrRPO6TRb/Ehy0dea6rzD093ydD24mPNsVh/uYrO+e25n8AFMhxy9LUePFB641KqQzYU4zbb8qEU2P9iXtL0KfdYGhrfe9kip7zqNs8sKLi22I5RCAeWvNhm7rd2htDbJmRqbAUr+ElLWSX12vi/qV+7v7dmJZeN92Z2OYcmxuruX91jd5I/L7Z5Stv9/ZLv7srsNSP1/rPDeZ/Fo7d4HLPnvlC/+uXIabvLqN/eXFqNFCAAA

**Comment by theastrogoth** [comment]
In the interest of getting things organized for now, I'll save Choice Locking, Non-Volatile Statuses, and the other to-dos for another PR

**Pull request merged**
